x.argsort()
将x中的元素从小到大排列，提取其对应的index(索引)，然后输出到y，y的值是x从小到大的序号
BB = BB[sorted_ind, :]
降序排列

In [10]:
import numpy as np
# np.round() #取整
# np.where() 

# 广播 #

广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在相应的元素上进行。

如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的长度相同。当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。如：


In [1]:
import numpy as np 

a = np.zeros((3,5,2))
a[:2,4,:] = [1,2]
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [1. 2.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [1. 2.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [2]:
import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([0,1,2])
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


常用的api

In [16]:
numpy_array = np.ones([2,2])

#np.ndim
print(numpy_array.ndim) # 输出np数组的维度

#np.tile
print(np.tile(numpy_array[:,:,None],3).shape)
print(np.tile(numpy_array,3).shape)


2
(2, 2, 3)
(2, 6)
